Repository torus/42-minishell, pull requests merged in 2021-05, with the labels that each got.

#76 シグナルハンドリングの追加
  Makefile
  cmd_exec_command.c
  minishell.c
  minishell.h
  signal.c
  test/Makefile
Labels: enhancement

#77 ビルトインコマンドの実装
  Makefile
  builtin.c
  builtin.h
  builtin_cd.c
  builtin_echo.c
  builtin_env.c
  builtin_exit.c
  builtin_export.c
  builtin_pwd.c
  builtin_unset.c
  cmd_cmd_invocation.c
  cmd_exec_command.c
  cmd_exec_commands.c
  cmd_pid.c
  cmd_redirection.c
  convert_ast2cmdinvo.c
  env.h
  env_setter.c
  execution.h
  minishell.h
  minishell_error_msg.c
  test/Makefile
  test/env_test.c
Labels: enhancement

#81 `cd`コマンドをbashの仕様に合わせる
  Makefile
  builtin.h
  builtin_cd.c
  builtin_cd_cdpath.c
  builtin_cd_chdir.c
  builtin_cd_path.c
  builtin_exit.c
  builtin_pwd.c
  env.c
  env.h
  g_cwd.c
  path.c
  path.h
  test/Makefile
  test/env_test.c
  test/exec_test.c
  test/path_test.c
Labels: bug

#82 コマンド実行の修正
  builtin_cd_cdpath.c
  cmd_exec_command.c
  cmd_exec_commands.c
  env.c
  env.h
  exec.c
  minishell_error_msg.c
  path.c
  path.h
  test/command_exec_test.c
  test/env_test.c
  test/exec_test.c
Labels: bug

#90 ディスクリプタ付きリダイレクションの実装
  cmd_cmd_invocation.c
  cmd_redirection.c
  convert_ast2cmdinvo.c
  execution.h
  test/ast2cmdinvo_test.c
  test/command_exec_test.c
Labels: enhancement

#92 バックスラッシュを使った文字のエスケープ
  lexer.h
  lexer1.c
  lexer2.c
  lexer3.c
  minishell.c
  parse.h
  parse_utils.c
  test/ast2cmdinvo_test.c
  test/parse_test.c
Labels: bug

#95 ASTからcmdinvoへの変換でエスケープに対応させる.
  Makefile
  builtin_cd_chdir.c
  expand_env_var.c
  expand_string_node.c
  libft/libft.h
  libft/ptrarr_utils2.c
  minishell.h
  split_expanded_str.c
  str_utils.c
  string_node2string.c
  test/Makefile
  test/ast2cmdinvo_test.c
  test/parse_test.c
  test/test.c
  test/test.h
  utils.h
Labels: bug

#98 必要なヘッダーファイルを *.h に全て書かない.
  builtin.c
  builtin.h
  builtin_cd.c
  builtin_cd_cdpath.c
  builtin_cd_chdir.c
  builtin_echo.c
  builtin_env.c
  builtin_exit.c
  builtin_export.c
  builtin_unset.c
  cmd_exec_command.c
  cmd_exec_commands.c
  cmd_redirection.c
  env.c
  env.h
  env_setter.c
  exec.c
  execution.h
  expand_env_var.c
  g_cwd.c
  minishell.c
  minishell.h
  path.c
  path.h
  signal.c
  test/ast2cmdinvo_test.c
  test/env_test.c
  test/path_test.c
Labels: enhancement

#99 シェルの初期設定を行う
  Makefile
  minishell.c
  minishell.h
  shell_initialization.c
  test/Makefile
Labels: enhancement

#100 MacOS 上でもコンパイル出来るようにした
  Makefile
  minishell.h
  signal.c
Labels: enhancement

#103 exit の値をbashの動作と同じようにする.
  builtin_exit.c
  libft/ft_atoi.c
  libft/libft.h
Labels: bug

#105 複数fdのリダイレクションに対応
  Makefile
  cmd_exec_builtin.c
  cmd_exec_commands.c
  cmd_redirection.c
  execution.h
  test/Makefile
  test/command_exec_test.c
Labels: enhancement

#106 INT_MAX 超えるfdが渡されたらリダイレクションのfdではなくコマンドライン引数として処理する
  cmd_exec_builtin.c
  cmd_redirection.c
  cmd_status.c
  env.h
  execution.h
  lexer3.c
  libft/ft_atoi.c
  libft/libft.h
  test/parse_test.c
Labels: bug

#109 exportの挙動をbashに合わせる
  Makefile
  builtin.h
  builtin_export.c
  builtin_export2.c
  env_setter.c
  libft/Makefile
  libft/libft.h
  libft/strarr_utils.c
  shell_initialization.c
  test/Makefile
Labels: bug

#72 コマンド行エディタ
  .gitignore
  Makefile
  editor.h
  editor1.c
  editor2.c
  editor3.c
  editor4.c
  editor5.c
  lexer1.c
  minishell.c
  minishell.h
  parse.h
  rope.h
  rope1.c
  rope2.c
  rope3.c
  rope4.c
  splay1.c
  splay2.c
  splay3.c
  splay4.c
  test/.gitignore
  test/Makefile
  test/ast2cmdinvo_test.c
  test/parse_test.c
  test/rope_test.c
  test/splay_test.c
Labels: enhancement

#115 シェル変数の実装
  Makefile
  builtin_cd.c
  builtin_cd_cdpath.c
  builtin_cd_chdir.c
  builtin_env.c
  builtin_exit.c
  builtin_export.c
  builtin_export2.c
  builtin_pwd.c
  cmd_status.c
  env.c
  env.h
  env_setter.c
  exec.c
  expand_env_var.c
  g_cwd.c
  minishell.c
  minishell.h
  shell_initialization.c
  t_var.c
  t_var2.c
  test/Makefile
  test/ast2cmdinvo_test.c
  test/command_exec_test.c
  test/env_test.c
  test/exec_test.c
  test/path_test.c
Labels: enhancement

#120 export で表示される環境変数の値に特殊文字が入っている時にエスケープする
  builtin_export2.c
Labels: bug

#124 SHLVLが1000を超える場合には警告メッセージと共にSHLVLを1にセットする
  shell_initialization.c
Labels: bug

#126 ダブルクオート内のエスケープの挙動を修正
  lexer3.c
Labels: bug

#127 閉じてないクォートや行末のバックスラッシュで死なないように修正
  lexer.h
  lexer1.c
  lexer2.c
  lexer3.c
  test/Makefile
  test/parse_test.c
Labels: bug

#128 関数コメントを全て英語に書き換えた
  builtin.c
  builtin.h
  builtin_cd.c
  builtin_cd_cdpath.c
  builtin_cd_chdir.c
  builtin_cd_path.c
  builtin_export.c
  builtin_unset.c
  cmd_exec_builtin.c
  cmd_exec_command.c
  cmd_exec_commands.c
  cmd_redirection.c
  cmd_status.c
  convert_ast2cmdinvo.c
  env.c
  env.h
  env_setter.c
  exec.c
  execution.h
  expand_env_var.c
  expand_string_node.c
  g_cwd.c
  minishell.h
  minishell_error_msg.c
  path.c
  shell_initialization.c
  signal.c
  split_expanded_str.c
  str_utils.c
  string_node2string.c
  t_var.c
  t_var2.c
Labels: invalid
