Repository torus/42-minishell, pull requests merged in 2021-06, with the labels that each got.

#130 プロンプト表示と長い行の編集時の問題を修正
  Makefile
  editor.h
  editor1.c
  editor2.c
  editor3.c
  editor4.c
  editor5.c
  editor6.c
  minishell.h
  signal.c
Labels: bug

#131 構文エラーのときにエラーメッセージを表示して終了ステータスを 1 にセットする
  editor1.c
Labels: bug

#134 Ctrl-D とシグナルハンドラの処理
  Makefile
  editor.h
  editor1.c
  editor2.c
  editor4.c
  editor5.c
  editor6.c
  editor7.c
  minishell.h
  shell_initialization.c
  signal.c
  test/Makefile
Labels: bug

#135 履歴を編集するときはコピーオンライトで新しい履歴を追加する。
  editor.h
  editor1.c
  editor2.c
  editor3.c
  editor6.c
  editor7.c
Labels: bug

#136 Rope の操作でたまに文字列が壊れるのを修正。
  rope1.c
  test/rope_test.c
  test/test.h
Labels: bug

#137 セミコロンで終わるコマンド行でエラーにならないように修正。
  parse.h
  parse1.c
  test/parse_test.c
Labels: bug

#139 長い行に対応。
  lexer2.c
  parse.h
  test/ast2cmdinvo_test.c
  test/parse_test.c
  test/test.h
Labels: bug

#140 リダイレクションとパイプの構文エラーの検出。
  parse.h
  parse1.c
  parse2.c
  parse_utils2.c
  test/parse_test.c
Labels: bug

#141 長い環境変数名でも正しく値に置き換えることができる
  editor1.c
  lexer.h
  lexer2.c
  lexer3.c
  minishell.c
  parse.h
  test/ast2cmdinvo_test.c
  test/parse_test.c
Labels: bug

#148 ヒアドキュメントのパーサ
  Makefile
  lexer.h
  lexer1.c
  lexer4.c
  parse.h
  parse1.c
  parse2.c
  parse3.c
  parse_utils.c
  parse_utils2.c
  test/Makefile
  test/parse_test.c
Labels: enhancement

#147 termcapではなくreadlineを使って読み込み, 履歴の機能を実装する
  Makefile
  editor.h
  editor1.c
  editor2.c
  editor3.c
  editor4.c
  editor5.c
  editor6.c
  editor7.c
  interactive_shell.c
  minishell.c
  minishell.h
  parse.h
  rope.h
  rope1.c
  rope2.c
  rope3.c
  rope4.c
  shell_initialization.c
  signal.c
  splay1.c
  splay2.c
  splay3.c
  splay4.c
  splay5.c
  splay6.c
  test/Makefile
Labels: enhancement

#150 rope_testとsplay_testを削除
  test/rope_test.c
  test/splay_test.c
Labels: Refactor

#151 コマンド実行部分でのheredocの実装
  Makefile
  builtin_exit.c
  builtin_export.c
  builtin_fd_list.c
  cmd_cmd_invocation.c
  cmd_cmd_invocation2.c
  cmd_exec_builtin.c
  cmd_exec_command.c
  cmd_exec_commands.c
  cmd_heredoc_funcs.c
  cmd_pipe.c
  cmd_redirection.c
  convert_ast2cmdinvo.c
  env.h
  env_expander.c
  execution.h
  heredoc_expander.c
  interactive_shell.c
  minishell.c
  minishell.h
  minishell_error_msg.c
  parse_utils2.c
  string_node2string.c
  test/Makefile
  test/ast2cmdinvo_test.c
  test/command_exec_test.c
  test/parse_test.c
Labels: enhancement

#152 exportコマンドの時の環境変数展開の動きをbashに合わせる.
  convert_ast2cmdinvo.c
  expand_string_node.c
  minishell.h
  test/ast2cmdinvo_test.c
Labels: enhancement

#155 スペースもしくはコントロール文字のみのときは "Parse Error" を表示しない
  interactive_shell.c
Labels: bug

#156 heredocの入力先fdが1以外のときにも正しく動作する
  cmd_redirection.c
Labels: bug

#159 env関数の中で生成したenvironをきちんとfreeする
  builtin_env.c
Labels: bug

#160 複数fdのheredoc対応を行った
  Makefile
  cmd_cmd_invocation.c
  cmd_cmd_invocation2.c
  cmd_exec_builtin.c
  cmd_exec_command.c
  cmd_exec_commands.c
  cmd_pipe.c
  cmd_redirection.c
  execution.h
  fd_reds_list_utils.c
  t_cmd_redirection.c
  test/Makefile
  test/ast2cmdinvo_test.c
  test/exec_test.c
Labels: enhancement
